#!/bin/sh
if [ "$(whoami)" = "root" ]; then
  echo "Setting Register to disable BD PROCHOT..."
  wrmsr 0x1FC "$(expr "$(rdmsr -a -d 0x1FC)" - 1)"
else
  echo "Please run this script as root."
  exit 1
fi
